import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '~/lib/utils';
import { QueryProvider } from '~/components/providers/query-provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Thalorra',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='light'>
      <body
        className={cn(
          'text-foreground overscroll-none font-sans antialiased',
          inter.className
        )}
      >
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
